### ISSUE TITLE
'_layout/archive.html' layout

### ISSUE THREAD

**Issue by dwlfrth** [Phlow/simplicity#1]
More like a question than an issue.

Not quite sure why there's a differentiation of line item `<li>` of the `if forloop.last` affecting the subheading of a post (around line 24 of `_layouts/archive.html`).

Shouldn't it simply be
`<ul class="toc">
    {% for post in site.posts %}
        <li><a href="{{ site.url }}{{ site.baseurl }}{{ post.url }}">{% if post.subheadline %}<span>{{ post.subheadline }}</span>{% endif %}{{ post.title }}</a></li>
    {% endif %}
{% endfor %}
</ul>`

I adjusted mine and it seems to behave correctly, unless I'm wrong...
https://github.com/dwlfrth/dwlfrth.github.io/blob/master/_layouts/archive.html#L31

**Comment by Phlow** [comment]
Hey @dwlfrth – Sorry for my late response. You are totally right. The `if forloop.last` is not neaded at all and there was on top of it a mistake. Thankyou!

Here is the new code

```
<ul class="toc">
{% for post in site.posts %}
    <li><a href="{{ site.url }}{{ site.baseurl }}{{ post.url }}">{% if post.subheadline %}<span>{{ post.subheadline }}</span>{% endif %}{{ post.title }}</a></li>
{% endfor %}
</ul>
```
