### ISSUE TITLE
google font imports not working, please explain?

### ISSUE THREAD

**Issue by sudorifix** [Phlow/simplicity#10]
Hi Moritz.

Probably just a Jekyll n00b question, but can you explain how the font: import: command works in the config.yml file?
I've attempted adding 3 new google fonts to the theme using the syntax as supplied in config.yml (ie font: import: 'name: weight...')
I get the feeling from elsewhere online that I need to either upload the font files to the assets directory or at least directly call the google source url. However your theme assets directory doesn't already contain the OOTB font files (Roboto, Fira Sans etc), and I can't find an scss file that references any font source urls. So I can't see a relevant pattern that should be followed for this theme.

My additions to the config.yml are: 
font:
import: 'Averia+Libre:400,700' // font-family-serif
import: 'Expletus+Sans:400,400italic,500,500italic,600,600italic,700,700italic' // header-font-family
import: 'Open+Sans:400,400italic,600,600italic,700,700italic' // base-font-family

Many thanks,
Jess

**Comment by Phlow** [comment]
Hey Jess!

It works like this:

Your settings in config are stored in a variable. Than this variable is used in

_https://github.com/Phlow/simplicity/blob/gh-pages/_includes/helper/_1_head.html_

To import the font and than it is used in…

 this file:

*https://github.com/Phlow/simplicity/tree/gh-pages/assets/css*

Now the variable sets another _this time_ SASS-variable to your desired font:

~~~
/* Font Families */
$font-family-serif:         {{ site.font.font-family-serif }}
$font-family-sans-serif:    {{ site.font.font-family-sans-serif }}
$base-font-family:          {{ site.font.base-font-family }}
$font-family-monospace:     {{ site.font.font-family-monospace }}
$header-font-family:        {{ site.font.header-font-family }}
~~~

Than the SASS-variable is used in the SASS-Files under 

_https://github.com/Phlow/simplicity/tree/gh-pages/_sass/04_typography_

It's a little bit around the corner, but more convenient to adjust the theme to your liking )

Enjoy!

Moritz
