### ISSUE TITLE
"Show All Articles" is being displayed even when not necessary

### ISSUE THREAD

**Issue by arjunmayilvaganan** [Phlow/simplicity#13]
Let us say that there are 10 articles in total.

I feel that it is better if we hide "Show All Articles", if all the 10 articles end up getting displayed in the first page itself (when `posts_with_teaser_limit: 1` and `posts_list_limit: 15` - upto 16 can be displayed in first page).

Let me know what you think. I have a fix ready; I can submit a Pull request.

**Comment by Phlow** [comment]
That's a good idea. Submit a pull request and I add it. Thank you :)

**Comment by arjunmayilvaganan** [comment]
Hi @Phlow, I just submitted #14 
Let me know if you have any suggestions!
