### ISSUE TITLE
Suggestion: Add table environment

### ISSUE THREAD

**Issue by topofocus** [Phlow/simplicity#15]
I noticed, that tables are not rendered satisfactorily.

And found a simple solution. Suggesting to include it  either into the code or as customizing option to the documentation

There is a table-scss   Github project.
https://github.com/jwebcat/tables-sass

1. copy the `_tables.scss` file from the scss directory of that project  to   the sass/05_layout directory of simplicity.
2. add  ` :@import "tables" `   `to sass/00_layout.scss`   (@ row 27)
3. change the table section  of`sass /04_typography/_general_typography.scss` to
```
/* Tables
------------------------------------------------------------------- */
table{
        @extend %table;
/*      @extend %table-bordered;  */
        @extend %table-condensed;
  font-family: $font-family-sans-serif;
  font-size: .75em;}
 /*  stripes */
table   tr:nth-of-type(even) {
    background: rgba(0,0,0,.2)
}
td {
  vertical-align: top;
}
```

That fits beautiful into the theme and to it philosophy as well.

**Comment by Phlow** [comment]
Hey @topofocus, I am so sorry, I had no time, but I used your suggestions and it looks great :) Thank you! Stay healthy, mo.

Have a look at <https://phlow.github.io/simplicity/table/> :)
