### ISSUE TITLE
Navigation links broken

### ISSUE THREAD

**Issue by Pradhyo** [Phlow/simplicity#4]
Links are broken in the [navigation page](https://phlow.github.io/simplicity/navigation/)       

I checked site.url, site.baseurl from [here](https://github.com/Phlow/simplicity/blob/gh-pages/_config.yml#L36).        
Based on the links in the [navigation page](https://github.com/Phlow/simplicity/blob/gh-pages/_data/navigation_page.yml) and the conditions [here](https://github.com/Phlow/simplicity/blob/gh-pages/_includes/helper/navigation.html#L9) I am not sure how it is broken.

**Comment by Phlow** [comment]
Sorry for coming back so late @Pradhyo – I fixed it.
