### ISSUE TITLE
Error building simplicity

### ISSUE THREAD

**Issue by gpaulissen** [Phlow/simplicity#9]
When I type 

Type bundle exec jekyll serve --config _config.yml,_config_dev.yml

I get: 

            Error: could not read file /Users/gpaulissen/Documents/GitHub/simplicity-gh-pages/vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.

The solutions is to add the vendor directory to the exclude tag in _config.yml:

exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
    - vendor

**Comment by Phlow** [comment]
@gpaulissen Thank you for your help. Does it work now?
